# Generated by Django 4.1.3 on 2023-05-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='address',
            field=models.CharField(default='Indore', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='contact',
            field=models.IntegerField(default=957687789),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(default='Jitendra', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('REACTJS', 'ReactJS'), ('QA', 'Qa')], default='REACTJS', max_length=100),
            preserve_default=False,
        ),
    ]
