# Generated by Django 4.1.3 on 2023-05-30 10:13

import ckeditor_uploader.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, choices=[('PYTHON IT', 'Python IT'), ('REACTJS IT', 'ReactJS IT'), ('QA IT', 'QA IT'), ('PYTHON NON-IT', 'Python NON-IT'), ('REACTJS NON-IT', 'ReactJS NON-IT'), ('QA NON-IT', 'QA NON-IT')], max_length=100, null=True)),
                ('title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Python')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Description about courses')),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('students_enrolled', models.PositiveIntegerField(default=0)),
                ('job_guarantee', models.CharField(blank=True, max_length=100)),
                ('online_classes', models.CharField(blank=True, max_length=100)),
                ('offline_classes', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('skills', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('NON-IT', 'Non-IT')], default='IT', max_length=20)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='media/courses/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatYouLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('whatyoulearn_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='whatyoulearn_description')),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courses')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TheseCourseIsForYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='TheseCourseIsForYou About')),
                ('specification', models.TextField(blank=True, null=True)),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(blank=True, max_length=300, null=True)),
                ('chapter_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='description')),
                ('syllabus_image', models.ImageField(blank=True, null=True, upload_to='media/courses/syllabus_image/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='SubSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_chapter', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='description')),
                ('subchapter_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='description')),
                ('sub_syllabus_image', models.ImageField(blank=True, null=True, upload_to='media/courses/sub_syllabus_image/')),
                ('is_active', models.BooleanField(default=True)),
                ('syllabus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_path_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='career_path_description')),
                ('career_path_image', models.ImageField(blank=True, null=True, upload_to='media/courses/career_path_image/')),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='AboutCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('aboutcourse_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='aboutcourse_description')),
                ('about_course_image', models.ImageField(blank=True, null=True, upload_to='media/courses/about_course_image/')),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courses')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
